### PR TITLE
`use v6` must be on the first line

### PR DESCRIPTION
**Pull request by AlexDaniel**

### CODE REVIEW

**Comment by dginev** [comment]
Thanks!

**Comment by dginev** [comment]
@AlexDaniel do you have an up-to-date Travis-CI build script for this type of module? I haven't checked in in a long while, and noticed `panda` has been deprecated for `zef`. Probably best to keep the builds here green.

**Comment by AlexDaniel** [comment]
@dginev see this https://docs.travis-ci.com/user/languages/perl6/#examples

**Comment by dginev** [comment]
Thanks, did the trick. Seems I'll have to learn some zef to get the tests going again, should be fun.

https://travis-ci.org/dginev/perl6-Lingua-EN-Sentence/jobs/455212884

**Comment by AlexDaniel** [comment]
> MoarVM panic: Register types do not match between value and node

This is an issue in rakudo. See https://github.com/rakudo/rakudo/issues/2477.

**Comment by dginev** [comment]
Oh cool, you saved me some grief. Tracking the issue now, will rebuild after it's solved. Thanks again!

**Pull request merged**
